<a href="https://colab.research.google.com/github/darshan9hegde/fast_marching/blob/main/fast_marching.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install -q condacolab
import condacolab
condacolab.install()

⏬ Downloading https://github.com/jaimergp/miniforge/releases/latest/download/Mambaforge-colab-Linux-x86_64.sh...
📦 Installing...
📌 Adjusting configuration...
🩹 Patching environment...
⏲ Done in 0:00:20
🔁 Restarting kernel...


In [1]:
!conda --version

conda 4.14.0


In [2]:
!which conda

/usr/local/bin/conda


In [3]:
!conda install -c conda-forge igl

Solving environment: | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - done

## Package Plan ##

  environment location: /usr/local

  added / updated specs:
    - igl


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2022.9.24  |       ha878542_0         150 KB  conda-forge
    certifi-2022.9.24          |     pyhd8ed1ab_0         155 KB  conda-forge
    conda-22.9.0               |   py37h89c1867_1         960 KB  conda-forge
    igl-2.2.1                  |   py37h9d0810c_1        10.8 MB  conda-forge
    libblas-3.9.0              |16_linux64_openblas          13 KB  conda-forge
    libcblas-3.9.0             |16_linux64_openblas          13 KB  conda-forge
    libgfortran-ng-12.1.0      |      h69a702a_16          23 KB  conda-forge
    libgfortran5-12.1.0        |      hdcd56e2

In [4]:
!conda install -c conda-forge meshplot 

Solving environment: | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | done

## Package Plan ##

  environment location: /usr/local

  added / updated specs:
    - meshplot


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    attrs-22.1.0               |     pyh71513ae_1          48 KB  conda-forge
    backcall-0.2.0             |     pyh9f0ad1d_0          13 KB  conda-forge
    backports-1.0              |             py_2           4 KB  conda-forge
    backports.functools_lru_cache-1.6.4|     pyhd8ed1ab_0           9 KB  conda-forge
    brotli-1.0.9               |       h166bdaf_7          18 KB  conda-forge
    brotli-bin-1.0.9           |       h166bdaf_7          19 KB  conda-forge
    cycler-0.11.0              |     pyhd8ed1ab_0          10 KB  conda-forge
    debugpy-1.6.3            

In [5]:
!conda install meshplot

Solving environment: / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / done

# All requested packages already installed.

Retrieving notices: ...working... done


In [6]:
from google.colab import files
uploaded=files.upload()



Saving igea.ply to igea.ply


In [7]:
import igl
import meshplot as mp
import numpy as np

In [8]:
import igl
import scipy as sp
import numpy as np
from meshplot import plot, subplot, interact

import os
root_folder = os.getcwd()

In [9]:
from google.colab import output
output.enable_custom_widget_manager()

In [10]:
# loading and plotting mesh
vert, tri = igl.read_triangle_mesh("./igea.ply")
#plot_mesh = mp.plot(vert, tri)

In [11]:
vert: np.array
tri: np.array

In [12]:
#print(vert)
print(type(vert))
print(len(vert))

#print(tri)
print((tri))
#print(tri[77901])


<class 'numpy.ndarray'>
134345
[[     0      1      2]
 [     2      1      3]
 [     2      3      4]
 ...
 [134327 134331 134325]
 [ 10780 134335  10781]
 [133838 134344 133836]]


In [13]:
!python --version

Python 3.7.12


# **minHeap**

In [ ]:
# Python3 implementation of Min Heap

import sys
from itertools import repeat

class MinHeap:

    def __init__(self, maxsize):
      self.maxsize = maxsize
      self.size = 0
      self.Heap = [[]for i in repeat(None,maxsize)]
      for i in range (maxsize):
        self.Heap[i].append(i)
        self.Heap[i].append(float(sys.maxsize))
      self.Heap.insert(0,[0,(-sys.maxsize)])
      self.FRONT = 1
      self.Heap = np.array(self.Heap)

    # Function to return the position of
    # parent for the node currently
    # at pos
    def parent(self, pos):
        return pos//2

    # Function to return the position of
    # the left child for the node currently
    # at pos
    def leftChild(self, pos):
        return 2 * pos

    # Function to return the position of
    # the right child for the node currently
    # at pos
    def rightChild(self, pos):
        return (2 * pos) + 1

    # Function that returns true if the passed
    # node is a leaf node
    def isLeaf(self, pos):
        return pos*2 > self.size

    # Function to swap two nodes of the heap
    def swap(self, fpos, spos):
      
      self.Heap[fpos],self.Heap[spos]  = self.Heap[spos],self.Heap[fpos]
      
      

    # Function to heapify the node at pos
    def minHeapify(self, index):

        # If the node is a non-leaf node and greater
        # than any of its child

        if not self.isLeaf(index):
            if (self.Heap[index][1] > self.Heap[self.leftChild(index)][1] or
            self.Heap[index][1] > self.Heap[self.rightChild(index)][1]):

                # Swap with the left child and heapify
                # the left child
                if self.Heap[self.leftChild(index)][1] < self.Heap[self.rightChild(index)][1]:
                    self.swap(index, self.leftChild(index))
                    self.minHeapify(self.leftChild(index))

                # Swap with the right child and heapify
                # the right child
                else:
                    self.swap(index, self.rightChild(index))
                    self.minHeapify(self.rightChild(index))

    #Function to insert a node into the heap
    def remove_node(self,node):
      index = np.where(self.Heap==node)[0][0]
      self.Heap[index][1]=-1*sys.maxsize
      while self.Heap[index][1] < self.Heap[self.parent(index)][1]:
          self.swap(index, self.parent(index))
          index = self.parent(index)
      self.remove()



    def insert(self, element):
        index = np.where(self.Heap==element[0])[0][0]
        self.Heap[index][1]=-1*sys.maxsize
        while self.Heap[index][1] < self.Heap[self.parent(index)][1]:
            self.swap(index, self.parent(index))
            index = self.parent(index)
        self.remove()


        if self.size >= self.maxsize+10 :
            return
        self.size+= 1
        self.Heap[self.size] = element #element is an array with index and and priority

        current = self.size
        print('current is',current )

        print('self.Heap[current] is',self.Heap[current] )

        # print('self.Heap[self.parent(current)] is',self.Heap[self.parent(current)] )

        while self.Heap[current][1] < self.Heap[self.parent(current)][1]:
            self.swap(current, self.parent(current))
            current = self.parent(current)
        
        


    #if it is the existing node it inserts only the priority
    def insert_element(self,node,value):

      #in this position the Heap has this ""node"
      index = np.where(self.Heap==node)[0][0]
      print('index where the node is present in the Heap: ',index)


      if self.Heap[index][0]==node:
        self.Heap[index][1]=value
        print('the value of Heap at the index is : ',self.Heap[index])
        print('the value at parent of the index is : ',self.Heap[self.parent(index)][1])
        #self.minHeapify(index)
        print(self.Heap[index][1]<self.Heap[self.parent(index)][1])

        while self.Heap[index][1]<self.Heap[self.parent(index)][1]:

          self.Heap[index],self.Heap[self.parent(index)]  = self.Heap[self.parent(index)],self.Heap[index]
          # self.swap(index,self.parent(index))
          index= self.parent(index)
          
      else:
        print("enter the node that already exists")


    # Function to print the contents of the heap
    def Print(self):
        for i in range(1, (self.size//2)+1):
            print(" PARENT : "+ str(self.Heap[i])+" LEFT CHILD : "+
                                str(self.Heap[2 * i])+" RIGHT CHILD : "+
                                str(self.Heap[2 * i + 1]))

    # Function to build the min heap using
    # the minHeapify function
    def minHeap(self):

        for pos in range(self.size//2, 0, -1):
            self.minHeapify(pos)

    # Function to remove and return the minimum
    # element from the heap
    def remove(self):

        popped = self.Heap[self.FRONT]
        self.Heap[self.FRONT] = self.Heap[self.size]
        self.size-= 1
        self.minHeapify(self.FRONT)
        return popped

# # Driver Code
# if __name__ == "__main__":
    
#     print('The minHeap is ')
#     minHeap = MinHeap(15)
#     minHeap.insert([1,5])
#     minHeap.insert([2,3])
#     minHeap.insert([3,17])
#     minHeap.insert([4,10])
#     minHeap.insert([5,84])
#     minHeap.insert([6,19])
#     minHeap.insert([7,6])
#     minHeap.insert([8,22])
#     minHeap.insert([9,9])
#     print(minHeap.Heap)


In [ ]:
heap_= MinHeap(10)
#print(np.where(heap_.Heap==10)[0][0])

#heap_.insert([10,3])

heap_.remove_node(8)



#heap_.swap(4,10)
#print(np.where(heap_.Heap==10)[0][0])


#print(heap_.Heap[:15])
#print(heap_.Heap[3])

# darshan =[[1,2],[3,4],[5,6],[7,8]]
# def swap(list_,a,b):
#   list_[a],list_[b]=list_[b],list_[a]




#heap_.insert([8,0.0036])

print('heap after inserting [8,0.0036]: ', heap_.Heap)

# swap(darshan,0,3)
# print(darshan)



heap after inserting [8,0.0036]:  [[ 0.00000000e+00 -9.22337204e+18]
 [ 0.00000000e+00 -9.22337204e+18]
 [ 1.00000000e+00  9.22337204e+18]
 [ 2.00000000e+00  9.22337204e+18]
 [ 3.00000000e+00  9.22337204e+18]
 [ 4.00000000e+00  9.22337204e+18]
 [ 5.00000000e+00  9.22337204e+18]
 [ 6.00000000e+00  9.22337204e+18]
 [ 7.00000000e+00  9.22337204e+18]
 [ 3.00000000e+00  9.22337204e+18]
 [ 9.00000000e+00  9.22337204e+18]]


# **to find if there are obtuse angles**

In [14]:
import math
from math import pi

def find_angle(A,b,c):
   #finds angle around the point A
   cosine_angle = np.dot(np.array(b)-np.array(A), np.array(c)-np.array(A)) / (np.linalg.norm(np.array(b)-np.array(A)) * np.linalg.norm(np.array(c)-np.array(A)))
   angle = np.arccos(cosine_angle)
   return angle



def find_obtuse(tri):
  i=0;
  
  obtuse_array = []
  for j in range (len(tri)):
    A = find_angle(vert[tri[j][0]],vert[tri[j][2]],vert[tri[j][1]])
    B = find_angle(vert[tri[j][1]],vert[tri[j][2]],vert[tri[j][0]])
    C = find_angle(vert[tri[j][2]],vert[tri[j][0]],vert[tri[j][1]])

    obtuse= False

    if A>(pi/2):
      obtuse= True
      
    if B>(pi/2):
      obtuse= True
      
    if C>(pi/2):
      obtuse= True

    if obtuse == True:
      obtuse_array.append(j)
      
  obtuse_array =np.array(obtuse_array)
  return obtuse_array 

print(len(find_obtuse(tri)))

        

53937


# **updater**

In [15]:
from math import sqrt
def calc_distance(p1,p2):
  distance = sqrt((p1[0]-p2[0])**2+(p1[1]-p2[1])**2+(p1[2]-p2[2])**2)
  return distance

# d1= calc_distance(vert[0],vert[1])
# d2= calc_distance(vert[0],vert[2])
#finds the update procedure when there are 2 points given and 
#d1 is distance to x1 and d2 to x2 and d3 to x3 from  a source point
#x1 would be a vert[1]for example has to have a xyz component
def updater(x1,d1,x2,d2,x3,d3):
  u = abs(d1-d2)
  if d1>d2:
    a = calc_distance(x1,x3)
    b = calc_distance(x2,x3)
    
  if d2>=d1:
    b = calc_distance(x1,x3)
    a = calc_distance(x2,x3)
  
  theta = find_angle(x3,x2,x1)
  #print('variable a is ', a)
  A= a**2+b**2-2*a*b*math.cos(theta)
  B= 2*b*u*(a*math.cos(theta)-b)
  C= b**2*(u**2-a**2*math.sin(theta)**2)

  root_term = B**2-4*A*C

  if root_term < 0 :
    root_term =0



  t1= (-B+sqrt(root_term))/(2*A)
  t2= (-B-sqrt(root_term))/(2*A)

  t= max(t1,t2)

  if (u<t and a*math.cos(theta)<(b*(t-u)/t) and (b*(t-u)/t)< a/math.cos(theta)):
    d3 = min(d3,t+b)
  else:
    d3=min(d3,b+min(d1,d2),a+max(d1,d2))

  return d3

d1= 0.007333421810442922
d2= 0.0024707027817164866
print(updater(vert[46353],d1,vert[46354],d2,vert[46352],1000))
print (calc_distance(vert[0],vert[46355]))


# x1 is  46353
# d1 is  0.007333421810442922
# x2 is  46354
# d2 is  0.0024707027817164866
# x3 is  46352

0.010664486839020432
0.020786971913939613


# **neighbour dictionary**

In [16]:
def nbr_dict(vert,tri):
  nbr_dictionary = {}
  for i in range (len(vert)):
      index_i=np.where(tri==i)[0]
      #print('index_i of ', popped, 'is ', index_i)
      neighbour_i =np.unique(tri[index_i][np.where(tri[index_i]!=i)])
      nbr_dictionary[i]= neighbour_i
  return nbr_dictionary




In [17]:
# Save

np.save('my_dict.npy', nbr_dict(vert,tri)) 

# Load
read_dictionary = np.load('my_dict.npy',allow_pickle='TRUE').item()
# print(read_dictionary['hello']) # displays "world"

In [18]:
#print(type(read_dictionary))
print(read_dictionary[3])
print(read_dictionary[1])
print(read_dictionary[2])
print(read_dictionary[4])

[    1     2     4     5 46359 46366 46367]
[    0     2     3 46328 46359]
[    0     1     3     4 46324 46325 46326]
[    2     3     5     6 46324]


# **find neighbour**

In [19]:


def find_nbr(p,q):
  #where index p is present in tri
  # index_p=np.where(tri==p)[0]
  # #where q is present in tri
  # index_q = np.where(tri==q)[0]
  nbr_p = neighbour_list[p]
  #print(nbr_p)
  nbr_q = neighbour_list[q]
  #print(nbr_q)
  nbr_list=[]

  for i in nbr_p:
    if i==-1:
      continue
    for j in nbr_q:
      if i==j:
        nbr_list.append(i)

  return nbr_list


def replace(n,A):
  index = np.where(A==n)
  #print(index)
  for i in range (len(index[0])):
    position_2 = index[1][i]
    position_1 = index[0][i]
    A[position_1][position_2]= -1

  return A


# **replacing the visited neighbours by -1**

In [20]:

A = np.array([    1  ,   2  ,   -1 ])
B= np.array([    0  ,   1  ,   3   ,  4, 46324, 46325, 46326])
C= np.array([    0 ,    2  ,   3, 46328 ,46359])
D = np.array([    2 ,    3  ,   5   ,  6 ,46324])
some_dict ={3:A, 2:B,1:C,4:D}



def replace_visited(n, read_dict):
  nbr_array = read_dict[n]
  #print('nbrs of ',n, 'are ',nbr_array)
  for i in range (len(nbr_array)):
    if nbr_array[i]==-1:
      continue
    index= np.where(read_dict[nbr_array[i]]==n)[0][0]
    #print(index)
    #print('the element being changed is ', read_dict[nbr_array[i]][index])
        
    read_dict[nbr_array[i]][index] =-1
  
  return read_dict





print(replace_visited(3, some_dict))

{3: array([ 1,  2, -1]), 2: array([    0,     1,    -1,     4, 46324, 46325, 46326]), 1: array([    0,     2,    -1, 46328, 46359]), 4: array([    2,     3,     5,     6, 46324])}


In [21]:
read_dictionary = np.load('my_dict.npy',allow_pickle='TRUE').item()

In [23]:

neighbour_list = read_dictionary.copy()

print(neighbour_list[0])
# [84729 84731 84881 84891]

[    1     2 46326 46327 46328]


# **very slow**

In [ ]:
import math
from math import sqrt
import heapq
from heapq import _siftup, _siftdown, heapify,heappush,heappop



#[distance, node]
def fast_marching(vert,neighbour_list):
  visited_node =np.array([])
  visited_distance=np.array([])
  visited_dict={}
  unvisited= [i for i in range(1,len(vert),1)]
  #unvisited_tri= np.copy(tri)


  heap = []

  initialize=0
  z = 0

  # bool to check whether unvisited node is empty
  isNotEmpty = True
  while isNotEmpty:
    z=z+1
    print('number of iteration in WHIIIIIIIIIIILLLLLLLEEEEE loooooooooooooooooooop',z)
    print('length of the unvisited is',len(unvisited) )
    print('length of the            VISITED is', len(visited_node))
    
    #bool to check whether the popped node has already been added to visited node
    isInVisited_node = True

    #to start the loop when the visited node length is zero
    if (len(visited_node)==0):
      print('len(visited_node)==0')
      #index_0=np.where(tri==0)[0]
      neighbour_0 = neighbour_list[0]
      print('neighbours of 0 are ', neighbour_0)

      #iterating through the neighbours of zero
      for i in range(len(neighbour_0)):

        d=calc_distance(vert[neighbour_0[i]],vert[0])
    
        heappush(heap,[d,neighbour_0[i]])

      popped=heappop(heap)
      print('popped node is ',popped[1])

      # #if the popped node already exists then 
      
      visited_node= np.insert(visited_node,len(visited_node),-1)
      # #print('visited_node after appending',visited_node)
      visited_distance= np.insert(visited_distance, len(visited_distance),-1)
      
      # # print(unvisited)
      # # print(np.any(unvisited[:] == popped[1]))
      # unvisited.remove(popped[1])
    #after the first node has been added to the visited node
    else:
      #index_i=np.where(unvisited_tri==popped[1])[0]
      #print('index_i of ', popped, 'is ', index_i)
      #neighbour_i =np.unique(unvisited_tri[index_i][np.where(unvisited_tri[index_i]!=popped[1])]) #index on a vert array like 1st 2nd or 43632nd 
      #print('untrimmed neighbours are', neighbour_i)
      neighbour_i=neighbour_list[popped[1]]

      #remove 0 from the unvisited neighbours
      neighbour_i= np.delete(neighbour_i,np.where(neighbour_i==0))

      #remove -1 from unvisited neighbours
      neighbour_i= np.delete(neighbour_i,np.where(neighbour_i==-1))

      #visited_ones = []

      # for i in visited_node:
      #   if i in neighbour_i:
      #     visited_ones.append(i)
      
      # for i in visited_ones:
      #   neighbour_i = np.delete(neighbour_i,np.where(neighbour_i ==i))


      print('unvisited neighbours of all', popped, 'are ',neighbour_i )

      #for iterating through all the neighbours of an element
      for j in range (len(neighbour_i)):

        print('neighbour_i[j] is ', neighbour_i[j],'end')

        if popped[1]==neighbour_i[j]:
          nbr=[]
        else:
          nbr= find_nbr(popped[1],neighbour_i[j])
        if 0 in nbr:
          nbr.remove(0)
        #print('mutual nbrs of',popped[1],' and ',neighbour_i[j], 'is ',nbr)

        #find if there are any mutual neighbours with the jth neighbour in neighbour_i array and popped vertex which is the one chosen for being minimum
        #if there are no mutual neighbours calculate distance via dijkstra otherwise use fast marching
        if len(nbr)==0:
          distance = popped[0]+calc_distance(vert[popped[1]],vert[neighbour_i[j]])
          heappush(heap,[distance,neighbour_i[j]])
        else:
          #for iterating through the mutual neighbours maximum could be 2
          for k in nbr:
            print('currently iterating mutual nbr is  ', k)
            #to see if the mutual neighbours exist in the visited list

            if len(visited_node)<len(vert)/2:
              if k in visited_node and k!=0: #and k!=visited_node[len(visited_node)-1] 
                #print('came to the fast marching section')
                x1=vert[k]
                d1=visited_distance[np.where(visited_node==k)][0]
                x2=vert[popped[1]]
                d2=popped[0]
                x3 = vert[neighbour_i[j]]
                # d3_node_list = np.where(np.asanyarray(heap) == neighbour_i[j])[0]
                # d3_list =[]

                # for l in range (len(d3_node_list)):
                #   d3_list.append(heap[d3_node_list[l]][1])
                
                # d3 = min(d3_list)
                # print('d3 for neighbour_i[j] is ', d3)

                # print('x1 is ', k)
                # print('d1 is ', d1)
                # print('x2 is ', popped[1])
                # print('d2 is ', d2)
                # print('x3 is ', neighbour_i[j])

                distance = updater(x1,d1,x2,d2,x3,1000)
                heappush(heap,[distance,neighbour_i[j]])

              else:
                #print('neighbour_i[j] is ', neighbour_i[j],'end')             

                distance = calc_distance(vert[neighbour_i[j]],vert[popped[1]])
                heappush(heap,[distance,neighbour_i[j]])
            else:
              if k not in unvisited and k!=0: #and k!=visited_node[len(visited_node)-1] 
              #print('came to the fast marching section')
                x1=vert[k]
                d1=visited_distance[np.where(visited_node==k)][0]
                x2=vert[popped[1]]
                d2=popped[0]
                x3 = vert[neighbour_i[j]]
                # d3_node_list = np.where(np.asanyarray(heap) == neighbour_i[j])[0]
                # d3_list =[]

                # for l in range (len(d3_node_list)):
                #   d3_list.append(heap[d3_node_list[l]][1])
                
                # d3 = min(d3_list)
                # print('d3 for neighbour_i[j] is ', d3)

                # print('x1 is ', k)
                # print('d1 is ', d1)
                # print('x2 is ', popped[1])
                # print('d2 is ', d2)
                # print('x3 is ', neighbour_i[j])

                distance = updater(x1,d1,x2,d2,x3,1000)
                heappush(heap,[distance,neighbour_i[j]])

              else:
                #print('neighbour_i[j] is ', neighbour_i[j],'end')             

                distance = calc_distance(vert[neighbour_i[j]],vert[popped[1]])
                heappush(heap,[distance,neighbour_i[j]])

          
      #print('heap before popping ',heap)
      #popped = heappop(heap)
      #print('the old popped[1] is ',popped[1], 'end')

      visited_node= np.insert(visited_node,len(visited_node),popped[1])
      #print('visited_node after appending',visited_node)
      visited_distance= np.insert(visited_distance, len(visited_distance),popped[0])
      unvisited.remove(popped[1])
      neighbour_list = replace_visited(popped[1],neighbour_list)

      # to check how many times second for loop is iterating
      swli =0
      
      #while loop to set the right value to popped, i.e. keep popping untill 
      #you find the node that has not already been added to the visited node list
      while isInVisited_node:
        swli= swli+1
        print('second while loop iteration is ', swli)
        popped=heappop(heap)
        copy_popped = np.copy([popped])
        print('the NEWWW popped[1] is ',popped[1], 'end')

        if len(visited_node)<len(vert)/2:
          if not np.any(visited_node[:] == popped[1]):
            isInVisited_node = False 

        else:
          if np.any(unvisited[:] == popped[1]):
            isInVisited_node = False 



      # #if the popped one is not in the visited node already and in the unvisited node
      # # add it and remove it from vsited_node and unvisited respectively and also replace that ellement with -1 in unvisited_tri
      # if not np.any(visited_node[:] == popped[1]) and np.any(unvisited[:] == popped[1]):
      #   visited_node= np.insert(visited_node,len(visited_node),popped[1])
      #   print('visited_node after appending',visited_node)
      #   visited_distance= np.insert(visited_distance, len(visited_distance),popped[0])
      #   unvisited.remove(popped[1])
      #   unvisited_tri = replace(popped[1],unvisited_tri)

      # # but if the popped node is in the visited node pop it again and check if it is in the visited node 
      # #means keep popping untill you pop a node that is not in the visited node and then add it 
      # else:
      #   popped = heappop(heap)
      #   print('popped[1] is ',popped[1], 'end')


    if len(unvisited)==0:
      isNotEmpty= False
    else:
      isNotEmpty= True
  fast_marching_array = np.array([[visited_node],[visited_distance]])
  return fast_marching_array



fast_marching(vert,neighbour_list)


# ** faster**

In [ ]:
import math
from math import sqrt
import heapq
from heapq import _siftup, _siftdown, heapify,heappush,heappop



#[distance, node]
def fast_marching(vert,neighbour_list):
  visited_node =np.array([])
  visited_distance=np.array([])
  visited_dict={}
  #unvisited= [i for i in range(1,len(vert),1)]
  #unvisited_tri= np.copy(tri)


  heap = []

  initialize=0
  z = 0

  # bool to check whether unvisited node is empty
  isNotEmpty = True
  while isNotEmpty:
    z=z+1
    print('number of iteration in WHIIIIIIIIIIILLLLLLLEEEEE loooooooooooooooooooop',z)
    
    #bool to check whether the popped node has already been added to visited node
    isInVisited_node = True

    #to start the loop when the visited node length is zero
    if (len(visited_node)==0):
      print('len(visited_node)==0')
      
      neighbour_0 = neighbour_list[0]
      #print('neighbours of 0 are ', neighbour_0)

      #iterating through the neighbours of zero
      for i in range(len(neighbour_0)):

        d=calc_distance(vert[neighbour_0[i]],vert[0])
    
        heappush(heap,[d,neighbour_0[i]])

      popped=heappop(heap)
      #print('popped node is ',popped[1])

      # #if the popped node already exists then 
      
      visited_node= np.insert(visited_node,len(visited_node),-1)
      # #print('visited_node after appending',visited_node)
      visited_distance= np.insert(visited_distance, len(visited_distance),-1)
      

    #after the first node has been added to the visited node
    else:

      neighbour_i=neighbour_list[popped[1]]

      #remove 0 from the unvisited neighbours
      neighbour_i= np.delete(neighbour_i,np.where(neighbour_i==0))

      #remove -1 from unvisited neighbours
      neighbour_i= np.delete(neighbour_i,np.where(neighbour_i==-1))


      #print('unvisited neighbours of all', popped, 'are ',neighbour_i )

      #for iterating through all the neighbours of an element
      for j in range (len(neighbour_i)):

        #print('neighbour_i[j] is ', neighbour_i[j],'end')

        if popped[1]==neighbour_i[j]:
          nbr=[]
        else:
          #print (popped[1],neighbour_i[j])
          nbr= find_nbr(popped[1],neighbour_i[j])
        if 0 in nbr:
          nbr.remove(0)
        #print('mutual nbrs of',popped[1],' and ',neighbour_i[j], 'is ',nbr)

        #find if there are any mutual neighbours with the jth neighbour in neighbour_i array and popped vertex which is the one chosen for being minimum
        #if there are no mutual neighbours calculate distance via dijkstra otherwise use fast marching
        if len(nbr)==0:
          distance = popped[0]+calc_distance(vert[popped[1]],vert[neighbour_i[j]])
          heappush(heap,[distance,neighbour_i[j]])
        else:
          #for iterating through the mutual neighbours maximum could be 2
          for k in nbr:
            #print('currently iterating mutual nbr is  ', k)
            #to see if the mutual neighbours exist in the visited list

            
            if k in visited_dict and k!=0: #and k!=visited_node[len(visited_node)-1] 
              #print('came to the fast marching section')
              x1=vert[k]
              d1=visited_dict[k]
              x2=vert[popped[1]]
              d2=popped[0]
              x3 = vert[neighbour_i[j]]
              

              distance = updater(x1,d1,x2,d2,x3,1000)
              heappush(heap,[distance,neighbour_i[j]])

            else:
              #print('neighbour_i[j] is ', neighbour_i[j],'end')             

              distance = popped[0]+calc_distance(vert[neighbour_i[j]],vert[popped[1]])
              heappush(heap,[distance,neighbour_i[j]])
            

          
      #print('heap before popping ',heap)
      #popped = heappop(heap)
      #print('the old popped[1] is ',popped[1], 'end')

      visited_dict[popped[1]]=popped[0]
      # unvisited.remove(popped[1])
      neighbour_list = replace_visited(popped[1],neighbour_list)

      # to check how many times second for loop is iterating
      swli =0
      
      #while loop to set the right value to popped, i.e. keep popping untill 
      #you find the node that has not already been added to the visited node list
      while isInVisited_node:
        swli= swli+1
        print('second while loop iteration is ', swli)
        popped=heappop(heap)
        if popped[1]in visited_dict:
          if visited_dict[popped[1]]>popped[0]:
            visited_dict[popped[1]]= popped[0]
        #print('the NEWWW popped[1] is ',popped[1], 'end')

        
        if popped[1] not in visited_dict :
          isInVisited_node = False 

        


    if len(visited_dict)==len(vert)-2:
      isNotEmpty= False
    else:
      isNotEmpty= True

  
  return visited_dict



fast_marching(vert,neighbour_list)

Streaming output truncated to the last 5000 lines.
second while loop iteration is  2524
second while loop iteration is  2525
second while loop iteration is  2526
second while loop iteration is  2527
second while loop iteration is  2528
second while loop iteration is  2529
second while loop iteration is  2530
second while loop iteration is  2531
second while loop iteration is  2532
second while loop iteration is  2533
second while loop iteration is  2534
second while loop iteration is  2535
second while loop iteration is  2536
second while loop iteration is  2537
second while loop iteration is  2538
second while loop iteration is  2539
second while loop iteration is  2540
second while loop iteration is  2541
second while loop iteration is  2542
second while loop iteration is  2543
second while loop iteration is  2544
second while loop iteration is  2545
second while loop iteration is  2546
second while loop iteration is  2547
second while loop iteration is  2548
second while loop iterat

{46326: 0.0067207889564223555,
 46328: 0.006781377131496146,
 46357: 0.006931303582487395,
 46355: 0.007156149399863921,
 46356: 0.0035844454186419947,
 46703: 0.0071881399238817555,
 46353: 0.007333421810442922,
 46354: 0.0024707027817164866,
 46330: 0.007477936943161453,
 46329: 0.007502875151923127,
 46327: 0.0068167877579915475,
 46765: 0.006824548706054124,
 46790: 0.007321177944788161,
 46766: 0.006982517094985983,
 46767: 0.006976907110763298,
 46331: 0.006870540372359894,
 46333: 0.006961287608666757,
 46332: 0.006853344544748639,
 46707: 0.0071279146393765005,
 46705: 0.0063556651507586485,
 46706: 0.007664749366274255,
 46708: 0.005879861085461346,
 46807: 0.007830125805800836,
 46806: 0.008019062064472523,
 46352: 0.008093308826022348,
 46335: 0.00849572644196757,
 48133: 0.006052027612987453,
 46769: 0.00705534309807897,
 46768: 0.006976107949240883,
 46798: 0.007013108196115902,
 46794: 0.007058264208232569,
 46789: 0.006996958054170718,
 46709: 0.00696245849752492,
 46337

# New section

In [ ]:
test_list1 = []
test_list2 = np.array([[0,1],[1,3],[2,5]])
print(test_list2[-1])
  
# printing original lists
  
# Using pop() + index() + insert()
# Move one list element to another list
#res = test_list1.insert(len(test_list1), test_list2.pop(test_list2.index([1,3])))


index=np.where(tri==46326)[0]
neighbour_k = np.unique(tri[index][np.where(tri[index]!=46326)])

print(neighbour_k)
x=0
#print(len(vert))


#heap_= MinHeap(len(vert))

#heap_.insert_element(10,3)
# heap_.insert([1,0.3])
# heap_.Heap[3][1]=15
# heap_.Heap[4][1]=12
# heap_.Heap[5][1]=6
# heap_.minHeapify(4)

#print(heap_.Heap)
#index_i=np.where(heap_.Heap==40258)[0][0]


#print(heap_.Heap[index_i][1])

# flag = False



# # 0 in [item[0] for item in tri repeat(item[0])]

#print(vert)

a=np.array([1,2,3,4,5])
not np.any(a[:] == 6)
print(np.where(a==2)[0][0])
# for elem in a:
#   print(elem+1)

[2 5]
[    0     2 46325 46327 46703 46765]
1


In [ ]:
import heapq
from heapq import _siftup, _siftdown, heapify
from random import random, randrange, choice

h = []
heapq.heappush(h, [5.087, 1])
heapq.heappush(h,[7.187, 2])
heapq.heappush(h, [1.00, 3])
heapq.heappush(h, [3.89,4])
heapq.heappush(h, [8.87,5])
heapq.heappush(h, [2.45,6])
heapq.heappush(h, [2.963,7])
heapq.heappush(h, [6.456,8])
j=[]
heapq.heappush(j, 5.087)
heapq.heappush(j, 7.187)
heapq.heappush(j, 1.00)
heapq.heappush(j, 3.89)
heapq.heappush(j, 8.87)
heapq.heappush(j, 2.45)
heapq.heappush(j, 2.963)
heapq.heappush(j, 6.456)

pop=heapq.heappop(h)
#print(pop)
#print(h)
# print(j)
index=np.where(tri==46357)[0]
neighbour_i = np.unique(tri[index][np.where(tri[index]!=46326)])
# print(neighbour_i)

index_j=np.where(tri==46357)[0]
neighbour_j = np.unique(tri[index_j][np.where(tri[index_j]!=46357)])
neighbour_j= np.delete(neighbour_j,np.where(neighbour_j==46358))
print(neighbour_j)

list_nbr =[]

for i in neighbour_i:
  for j in neighbour_j:
    if i==j:
      list_nbr.append(i)
# print(list_nbr)
# print(index_j)
#print(tri[index_j])
# k=np.where(tri[index_j]==2)[0]
# print(tri[index_j][k])
index_i = np.where(tri==2)[0]
# print(index_i)

some_array= np.array([1,2,3,4])
some_array=np.insert(some_array, len(some_array),9)
#print(some_array)
#print(tri[:15])


NameError: ignored

In [ ]:
A_ = np.array([[1,2,3],[3,8,9],[2,5,8],[4,5,4]])


Q = np.where(A_==2)[0]

B_ =np.array([1,2,3,5,6])

print(np.where(B_==3)[0][0])

index=np.where(tri==4)[0]
neighbour_i = np.unique(tri[index][np.where(tri[index]!=4)])

print(neighbour_i)

# import time

# start = time.time()
# print("hello")
# end = time.time()
# print(end - start)

 

2
[    2     3     5     6 46324]
